name: Mimari otomasyon github action - azmisahin-software-web-architecture-automation

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - name: npm install, test
      run: |
        npm install
        npm run test --if-present
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'azmisahin-software-web-architecture-automation'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_651ebd1aac5c42749985728cc7c745b6 }}
        package: .